name: trigger

on:
  workflow_call:
    inputs:
      dockle:
        required: true
        type: string
      hadolint:
        required: true
        type: string
      java:
        required: true
        type: string
      node:
        required: true
        type: string
      ubuntu:
        required: true
        type: string
      self:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      token:
        required: false

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - run: echo DOCKE_VERSION=${{ inputs.dockle }} UBUNTU_VERSION=${{ inputs.ubuntu }} SELF=${{ inputs.self }} ...
